name: main

on:
  push:
    branches: [master, dev]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/pants/setup
            ~/.cache/pants/lmdb_store
            ~/.cache/pants/named_caches
          key: ${{ runner.os }}-
      - name: Bootstrap Pants
        run: |
          ./pants --version
      - name: Run main build runner
        env:
          CI_TOOL: github
          GITHUB_TOKEN: ${{ secrets.token }}
        run: ./tools/ci/core/build.sh