name: main

on:
  push:
    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run main build runner
        env:
          CI_TOOL: github
          GITHUB_TOKEN: ${{ secrets.token }}
        run: ./tools/ci/core/build.sh