name: main

on:
  push:
    branches: [test]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/pants/setup
            ~/.cache/pants/lmdb_store
            ~/.cache/pants/named_caches
          key: ${{ runner.os }}-
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Bootstrap Pants
        run: |
          ./pants --version
          ./pants test ::
      - name: Run main build runner
        env:
          CI_TOOL: github
          GITHUB_TOKEN: ${{ secrets.token }}
        run: ./tools/ci/core/build.sh
      - name: Upload pants log
        uses: actions/upload-artifact@v2
        with:
          name: pants-log
          path: .pants.d/pants.log
        if: always()