name: Build and Deploy services

on:
  push:
    branches: [test_matrix]

jobs:
  determine_changed_services:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.find-services.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/pants/setup
            ~/.cache/pants/lmdb_store
            ~/.cache/pants/named_caches
          key: ${{ runner.os }}-
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Bootstrap Pants
        run: |
          ./pants --version
      - name: Set env
        run: echo "OUTPUT=service_twoo" >> $GITHUB_ENV
      - id: find-services
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          ./tools/ci/core/build.sh
          echo "here is output ${{ env.OUTPUT }}"
          echo "::set-output name=matrix::{\"service\":[$OUTPUT]}"

  build_changed_services:
    needs: determine_changed_services
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.determine_changed_services.outputs.changed_services) }}
    steps:
      - name: build
        run: echo ${{ matrix.service }}

  deploy:
    needs: build_changed_services
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo deployed!

