name: services

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service to run workflow for'
        required: true
        default: 'service_one'


jobs:
  service_one:
    name: service_one
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache/pants/setup
          ~/.cache/pants/lmdb_store
          ~/.cache/pants/named_caches
        key: ${{ runner.os }}-
    - name: Bootstrap Pants
      run: |
        ./pants --version
    - name: Check BUILD files
      run: |
        ./pants tailor --check update-build-files --check