name: Build and Deploy service_one

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cache/pants/setup
            ~/.cache/pants/lmdb_store
            ~/.cache/pants/named_caches
          key: ${{ runner.os }}-
      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Bootstrap Pants
        run: |
          ./pants --version
      - name: Package / Run
        run: |
          ./pants run services/service_one::
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy to k8s
        run: echo deployed!