name: services

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service to run workflow for'
        required: true
        default: 'service_one'


jobs:
  service_one:
    name: ${{ github.event.inputs.service_name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          ~/.cache/pants/setup
          ~/.cache/pants/lmdb_store
          ~/.cache/pants/named_caches
        key: ${{ runner.os }}-
    - name: Setup Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Bootstrap Pants
      run: |
        ./pants --version
    - name: Package / Run
      run: |
        ./pants run ${{ github.event.inputs.service_name }}